# Generated by Django 4.2 on 2023-06-19 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('listelement', '0001_initial'),
        ('comment', '0002_comment_element'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='element',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='listelement.element'),
        ),
    ]
